{
 "title": "Energy efficiency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Mean pod energy index",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "exp(\r\n\t0.65 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", mode!=\"idle\"}[5m]) * 100)\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t) + 0.35 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(container_memory_usage_bytes{pod=\"$pod\"}) / sum(container_spec_memory_limit_bytes{pod=\"$pod\"}) * 100\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t) + 0.05 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(\r\n\t\t\t\t(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m]) or vector(1) + rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) or vector(1)\r\n\t\t\t) / (1024 * 1024)\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t)\r\n) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod energy index",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "exp(\r\n\t0.65 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", mode!=\"idle\"}[5m]) * 100)\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t) + 0.35 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(container_memory_usage_bytes{pod=\"$pod\"}) / sum(container_spec_memory_limit_bytes{pod=\"$pod\"}) * 100\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t) + 0.05 * ln(\r\n\t\t1000 * (\r\n\t\t\tsum(\r\n\t\t\t\t(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m]) or vector(1) + rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) or vector(1)\r\n\t\t\t) / (1024 * 1024)\r\n\t\t) / (\r\n\t\t\tsum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))\r\n\t\t)\r\n\t)\r\n) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Mean pod CPU usage (dynamic)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", mode!=\"idle\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU usage (dynamic)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"$pod\", mode!=\"idle\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "text",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 7 },
   "options": {
    "content": "This dashboard allows calculating the node energy index and workload energy index.\n\n**Energy index** is a number greater than zero reflecting the energy efficiency of a node or workload. The higher the energy index, the greater the energy efficiency.\n\nTo measure the node energy index, run a standard workload on the node. To increase result accuracy, there should be no other workloads on the node.   \nTo measure the workload energy index, run the workload being tested. To increase result accuracy, resources allocated for the workload should be consistent across different workloads.\n\nFor comparing node energy index and workload energy index, the same metrics are used for the pod.\n\n**Steps:**\n- Setup resource limits in Helm Chart for workload. For example:\n  ```yaml\n  limits:\n    cpu: \"5\"\n    memory: \"1024Mi\"\n    ephemeral-storage: \"600Mi\"\n  requests:\n    cpu: \"3\"\n    memory: \"800Mi\"\n    ephemeral-storage: \"500Mi\"\n  ```\n- Deploy the workload (standard workload for measuring node energy index or the investigated workload for workload energy index) in one pod on one node.\n- Select the workload's pod in the dashboard filters.\n- The workload should run for some time to accumulate metric data. The longer the measurement, the more accurate the energy index.\n- The average value of the energy index will be available in the \"Mean pod energy index\" panel.\n\n\n\n\n"
   }
  },
  {
   "title": "Mean pod memory usage",
   "type": "gauge",
   "description": "Set limit in helm chart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\"}) / sum(container_spec_memory_limit_bytes{pod=\"$pod\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "description": "Set limit in helm chart",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"$pod\"} / container_spec_memory_limit_bytes{pod=\"$pod\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean pod storage usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mb/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m]) + rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod storage usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m]) + rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean pod energy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod energy consumption (dynamic)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "irate(kepler_container_joules_total{pod_name=\"$pod\", mode=\"dynamic\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}